source "https://rubygems.org"

group :development do
  gem 'rake', '~> 12.3'
  gem 'jekyll', '~> 2.1'
  gem 'jekyll-page-hooks', '~> 1.2'
  gem 'jekyll-date-format', '~> 1.0'
  gem 'jekyll-sitemap', '~> 0.5.0'
  gem 'RedCloth', '~> 4.2.9'
  gem 'haml', '~> 4.0'
  gem 'rubypants', '~> 0.2.0'
  gem 'rb-fsevent', '~> 0.9'
  gem 'stringex', '~> 1.4.0'
  gem 'link-checker', '~> 0.7.2'

  require 'rbconfig'
  if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i
    gem 'wdm', '>= 0.1.0'
  end
end
